# Generated by Django 5.0 on 2024-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_pic', models.ImageField(blank=True, null=True, upload_to='employee/')),
            ],
        ),
    ]
