# Generated by Django 5.0 on 2024-01-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_employee_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
